### ISSUE TITLE
Host IP not working.

### ISSUE THREAD

**Issue by ssamjh** [ruany/litebans-php#11]
When trying to open the page I get this error: 
SQLSTATE[28000] [1045] Access denied for user 'sdweb'@'104.223.31.184' (using password: YES)

In my config I have specified another IP: http://pastebin.com/9jRyGAeK

**Comment by ruany** [comment]
Seems like your MySQL server is returning the client's IP address rather than its own.

I tested using the MySQL CLI client and saw my own IP address:

```
mysql -usdweb -ptest -h 198.245.50.224
ERROR 1045 (28000): Access denied for user 'sdweb'@'141.*.***.**' (using password: YES)
```

Not a web interface issue, closing.
