### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by AndGK** [ruany/litebans-php#12]
Where can I edit Month names? I looked all over the place and couldn't find it, please help :)

**Comment by ruany** [comment]
Month names are handled by the locale. If you want to translate them into another language, you can copy "lang/en_US.utf8.php"  to a file corresponding with your system locale, and change the "lang" option in settings.php.

Dates are handled by this function in inc/page.php:
```
    function millis_to_date($millis) {
        $ts = $millis / 1000;
        $result = strftime($this->settings->date_format, $ts);
        return $result;
    }
```
If you want to do something else to the month names, you can edit this function. This function returns the date from strftime, e.g. "August 4, 2016, 18:37".

**Comment by ruany** [comment]
I've made it much easier to translate month names. New option in settings.php:
```
        $this->date_month_translations = array(
            "January"   => "Month 1",
            "February"  => "Month 2",
            "March"     => "Month 3",
            "April"     => "Month 4",
            "May"       => "Month 5",
            "June"      => "Month 6",
            "July"      => "Month 7",
            "August"    => "Month 8",
            "September" => "Month 9",
            "October"   => "Month 10",
            "November"  => "Month 11",
            "December"  => "Month 12",
        );
```
