### ISSUE TITLE
Litebans php pages displaying raw code

### ISSUE THREAD

**Issue by Willmaster04** [ruany/litebans-php#19]
When I extracted all the files into my local disk and loaded them up with chrome I got this; this is from bans.php and it looks like this on my browser.  I have an xampp mysql database which works fine with the plugin in game and I have set the correct settings in settings.php as well; I can't figure out what's wrong

http://pastebin.com/pePCwZgV

**Comment by ruany** [comment]
Your web server is not configured properly, unfortunately I cannot help you with this.

**Comment by Willmaster04** [comment]
Ok so it should work on my webserver just fine if I have html 5?

**Comment by ruany** [comment]
HTML5 is irrelevant. A PHP web server is required, any version of PHP from PHP 5 to PHP 7 should work fine, as long as it has PDO database support.
