### ISSUE TITLE
Random 8

### ISSUE THREAD

**Issue by Untuned** [ruany/litebans-php#21]
There is a small number 8 at the top of every page in LiteBans.

Example: https://untuned.pw/180717000639.png

**Comment by ruany** [comment]
Cannot replicate on a local setup, does it happen with a fresh install?

**Comment by ruany** [comment]
Closing until someone else reports the same issue.

**Comment by Untuned** [comment]
Happened with a fresh install, I could send you my bootstrap css if that helps.

**Comment by Untuned** [comment]
Nevermind, error on my part.

https://untuned.pw/200717011148.png
