### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by TheTopCz** [ruany/litebans-php#31]
Hi, I found the error http://prntscr.com/hyqo0g

Link: http://banlist.northmania.cz/history.php?page=1&uuid=cd42815d-49d9-3adf-8154-bd1f22fadf77

Basically, do not see Penalty Type in http://banlist.northmania.cz/history.php?

Language: Czech

**Comment by ruany** [comment]
![](https://i.imgur.com/BNj7kQ5.png)
Can't replicate. I would recommend reinstalling the web interface completely.
