### ISSUE TITLE
Using MariaDB

### ISSUE THREAD

**Issue by mredus** [ruany/litebans-php#32]
Hello, I can not get the web interface to work. I just get a database error. I feel like it is because I am using MariaDB for litebans but that driver is not available in the config of the web interface. I have changed the password and user multiple times and still get the same error.

`
// Database information
        $this->host = 'localhost';
        $this->port = 3306;

        $database = 'ggmcbans';

        $username = 'ggmclbs';
        $password = --Omitted--

        // If you set a table prefix in config.yml, set it here as well
        $this->table_prefix = "lb1_";

        // Supported drivers: mysql, pgsql
        $driver = 'mysql';
`

![scn_zp0lcek7](https://user-images.githubusercontent.com/35316065/34801639-63ac40d2-f62f-11e7-949c-252af7b3096e.jpg)

**Comment by mredus** [comment]
If it helps, it is running on IIS 10 with all of the appropriate php extensions installed.

**Comment by ruany** [comment]
It has nothing to do with MariaDB I'm sure, I have two web interface setups using the mysql driver with MariaDB databases and no issues.

Are the plugin and the web interface hosted on the same machine?

Does the plugin successfully connect to the same database?

**Comment by mredus** [comment]
Yes the webui and the database are on the same machine. The plugin is hosted on another server and did successfully connect.

**Comment by ruany** [comment]
I'd recommend adding remote access permissions for localhost, your web server's IP, and '%' if nothing else works.

Besides that, if your username/password/database are correct, then I don't know what could cause the problem.

**Comment by mredus** [comment]
I just tried again with all of the same settings and it started working. Thanks for y'alls help though!
