### ISSUE TITLE
You can not see the player's skin

### ISSUE THREAD

**Issue by NonoxSoux** [ruany/litebans-php#34]
I have a problem and do not see the skin of the players, is there a problem with crafatar.com?
  ##http://prntscr.com/ik0xqi
Link: http://empireislands.es/bansky/bans.php

**Comment by ruany** [comment]
Already fixed by https://github.com/ruany/litebans-php/commit/a2abd7f782e95f9766266733409bc056ebeaa80c, update the web interface.

This only affects offline-mode servers.

**Comment by ruany** [comment]
Fixed again https://github.com/ruany/litebans-php/commit/88cc07540b4f86d8eec3a6338b29f871c5a0a3d1
