### ISSUE TITLE
Tables Not Found

### ISSUE THREAD

**Issue by JustTijn** [ruany/litebans-php#35]
My web page says that the tables aren't found.
https://gyazo.com/f3c5c5ca78a431360883ed4ab5bd1405

These are my configs:
SERVER CONFIG: https://pastebin.com/90jttqcU
WEBSERVER CONFIG: https://pastebin.com/TVw2GdAy

**Comment by ruany** [comment]
`# LiteBans config.yml generated by version 2.2.4`
Found your problem. Outdated plugin.
