### ISSUE TITLE
[question]: location of type-names

### ISSUE THREAD

**Issue by RedstoneFuture** [ruany/litebans-php#36]
The type-names  ("Ban", "Warn", "Mute ...") are not listed in the `lang/en_US.utf8.php` and I can find not in the web-files. Where I can find it? :)

**Comment by ruany** [comment]
https://github.com/ruany/litebans-php/blob/master/lang/en_US.utf8.php#L19

```
        $array["generic.ban"] = "Ban";
        $array["generic.mute"] = "Mute";
        $array["generic.warn"] = "Warning";
        $array["generic.kick"] = "Kick";
```

**Comment by RedstoneFuture** [comment]
I mean this:

![unbenannt](https://user-images.githubusercontent.com/4140635/40709921-a1dd6aee-63f7-11e8-96d4-b2974711155e.png)

`        $array["generic.ban"] = "Bann";`

**Comment by ruany** [comment]
Fixed https://github.com/ruany/litebans-php/commit/9218cdc430240ae9049736ffe982f6344331c0f7

**Comment by RedstoneFuture** [comment]
Thanks. :)
