### ISSUE TITLE
How to set up litebans plugin?

### ISSUE THREAD

**Issue by engrshahabuddin** [ruany/litebans-php#9]
I have already upload it into my web server.
Link: http://www.swiftmine.net/bans/
but it does not work.

Configuration of setting.php: 
-------------------------------------------
// Web interface language. Languages are stored in the "lang/" directory.
        $this->lang = 'en_US.utf8';

        // Server name, shown on the main page and on the header
        $this->name = '-------.org';

        // Clicking on the header name will send you to this address.
        $this->name_link = '#';

        // Database information
        $host = '127.0.0.1';
        $port = 8889;

        $database = '--------';

        $username = '---------';
        $password = '---------';

        // If you set a table prefix in config.yml, set it here as well
        $table_prefix = "litebans_";

        // Supported drivers: mysql, pgsql
        $driver = 'mysql';
******************* I can also give access to you.Please help me.******************

**Comment by ruany** [comment]
"Connection refused" means that there isn't a MySQL server running on 127.0.0.1 port 8889.
Double check host and port and try again.

I cannot personally set things up for you, sorry.

**Comment by engrshahabuddin** [comment]
Servers1 - Hub 2GConfig Filesconfig.yml
--------------------------------------------------------------------
THERE is MySQL server running.You can see below details-
sql:
  # MySQL, PostgreSQL, SQLite, and H2 are supported database drivers.
  driver: MySQL

  ## MySQL/PostgreSQL settings ##
  # If using SQLite/H2, the database will be stored in the LiteBans plugin folder,
  # and most of these settings won't apply.

  # Database server address.
  address: 127.0.0.1

  # Database name, username and password.
  database: 'mc_1'
  username: 'mc_1'
  password: '1143d76465'

  table_prefix: 'litebans_'

**Comment by ruany** [comment]
The plugin is connecting to 127.0.0.1 port 3306 (default port), not 8889.

**Comment by engrshahabuddin** [comment]
Now I am using below setting but nowt working:
------------------------------------------------------------------
// Web interface language. Languages are stored in the "lang/" directory.
        $this->lang = 'en_US.utf8';

        // Server name, shown on the main page and on the header
        $this->name = 'http://www.swiftmine.org/';

        // Clicking on the header name will send you to this address.
        $this->name_link = '#';

        // Database information
        $host ='127.0.0.1';
        $port = 3306;

        $database = 'mc_1';

        $username = 'mc_1';
        $password = '1143d76465';

        // If you set a table prefix in config.yml, set it here as well
        $table_prefix = "litebans_";

        // Supported drivers: mysql, pgsql
        $driver = 'mysql';

**Comment by ruany** [comment]
Same issue. There isn't a MySQL server running on the IP address you're trying to connect it to.

**Comment by engrshahabuddin** [comment]
THERE is MySQL server running.You can see below details-
sql:
# MySQL, PostgreSQL, SQLite, and H2 are supported database drivers.
driver: MySQL

## MySQL/PostgreSQL settings ##
# If using SQLite/H2, the database will be stored in the LiteBans plugin folder,
# and most of these settings won't apply.

# Database server address.
address: 127.0.0.1

# Database name, username and password.
database: 'mc_1'
username: 'mc_1'
password: '1143d76465'

table_prefix: 'litebans_'

**Comment by ruany** [comment]
If the website and plugin are running on two different machines, using 127.0.0.1 as host means that they are connecting to themselves, not the same host.
